export type Word = { w: string; hint: string; hintHard: string };
export type Category = {
  id: string;
  emoji: string;
  name: string;
  words: Word[];
};

export const CATEGORIES: Category[] = [
  {
    id: 'food',
    emoji: '🍕',
    name: 'Comidas & Bebidas',
    words: [
      { w: 'Pizza', hint: 'italiana clássica', hintHard: 'redonda' },
      { w: 'Sushi', hint: 'culinária japonesa', hintHard: 'cru' },
      { w: 'Feijoada', hint: 'prato típico do Brasil', hintHard: 'preta' },
      { w: 'Hambúrguer', hint: 'fast food', hintHard: 'recheado' },
      { w: 'Lasanha', hint: 'massa em camadas', hintHard: 'molho' },
      { w: 'Brigadeiro', hint: 'doce brasileiro', hintHard: 'chocolate' },
      { w: 'Pão de Queijo', hint: 'salgado mineiro', hintHard: 'quentinho' },
      { w: 'Açaí', hint: 'fruta amazônica', hintHard: 'roxo' },
      { w: 'Coxinha', hint: 'salgadinho', hintHard: 'frita' },
      { w: 'Tacos', hint: 'culinária mexicana', hintHard: 'crocante' },
      { w: 'Sorvete', hint: 'sobremesa gelada', hintHard: 'derrete' },
      { w: 'Café', hint: 'bebida quente', hintHard: 'preto' },
      { w: 'Cerveja', hint: 'bebida alcoólica', hintHard: 'gelada' },
      { w: 'Caipirinha', hint: 'drink brasileiro', hintHard: 'verde' },
      { w: 'Churrasco', hint: 'reunião de domingo', hintHard: 'fumaça' },
      { w: 'Tapioca', hint: 'café da manhã', hintHard: 'branca' },
      { w: 'Macarrão', hint: 'massa', hintHard: 'comprido' },
      { w: 'Refrigerante', hint: 'bebida doce', hintHard: 'borbulhante' },
      { w: 'Salada', hint: 'comida saudável', hintHard: 'verde' },
      { w: 'Chocolate', hint: 'doce', hintHard: 'marrom' },
      { w: 'Pastel', hint: 'feira', hintHard: 'frito' },
      { w: 'Picanha', hint: 'corte de carne', hintHard: 'churrasco' },
      { w: 'Mousse', hint: 'sobremesa aerada', hintHard: 'fofo' },
      { w: 'Hot Dog', hint: 'lanche', hintHard: 'salsicha' },
      { w: 'Suco de Laranja', hint: 'bebida natural', hintHard: 'cítrico' },
      { w: 'Vinho', hint: 'bebida alcoólica', hintHard: 'tinto' },
      { w: 'Tofu', hint: 'culinária asiática', hintHard: 'branco' },
      { w: 'Quibe', hint: 'culinária árabe', hintHard: 'frito' },
      { w: 'Esfiha', hint: 'culinária árabe', hintHard: 'aberta'  },
      { w: 'Cuscuz', hint: 'café da manhã nordestino', hintHard: 'amarelo' },
      { w: 'Doce de Leite', hint: 'doce caramelizado', hintHard: 'pastoso' },
      { w: 'Risoto', hint: 'arroz cremoso', hintHard: 'italiano' },
    ],
  },
  {
    id: 'animals',
    emoji: '🦁',
    name: 'Animais',
    words: [
      { w: 'Leão', hint: 'felino selvagem', hintHard: 'amarelo' },
      { w: 'Elefante', hint: 'mamífero gigante', hintHard: 'cinza' },
      { w: 'Tubarão', hint: 'predador marinho', hintHard: 'dentes' },
      { w: 'Águia', hint: 'ave de rapina', hintHard: 'voa alto' },
      { w: 'Cobra', hint: 'réptil', hintHard: 'rasteja' },
      { w: 'Tartaruga', hint: 'animal lento', hintHard: 'casco' },
      { w: 'Cachorro', hint: 'animal de estimação', hintHard: 'late' },
      { w: 'Gato', hint: 'animal de estimação', hintHard: 'mia' },
      { w: 'Cavalo', hint: 'animal de monta', hintHard: 'crina' },
      { w: 'Golfinho', hint: 'mamífero aquático', hintHard: 'inteligente' },
      { w: 'Pinguim', hint: 'ave que não voa', hintHard: 'gelo' },
      { w: 'Urso', hint: 'mamífero grande', hintHard: 'mel' },
      { w: 'Tigre', hint: 'felino listrado', hintHard: 'laranja' },
      { w: 'Macaco', hint: 'primata', hintHard: 'banana' },
      { w: 'Girafa', hint: 'animal alto', hintHard: 'pescoço' },
      { w: 'Zebra', hint: 'savana africana', hintHard: 'listras' },
      { w: 'Coelho', hint: 'orelhudo', hintHard: 'pula' },
      { w: 'Polvo', hint: 'molusco marinho', hintHard: 'oito' },
      { w: 'Aranha', hint: 'aracnídeo', hintHard: 'tece' },
      { w: 'Borboleta', hint: 'inseto colorido', hintHard: 'voa' },
      { w: 'Papagaio', hint: 'ave falante', hintHard: 'colorido' },
      { w: 'Capivara', hint: 'roedor brasileiro', hintHard: 'aquático' },
      { w: 'Onça', hint: 'felino brasileiro', hintHard: 'pintada' },
      { w: 'Lobo', hint: 'canino selvagem', hintHard: 'matilha' },
      { w: 'Raposa', hint: 'canino esperto', hintHard: 'avermelhada' },
      { w: 'Camelo', hint: 'animal de deserto', hintHard: 'corcova' },
      { w: 'Canguru', hint: 'animal australiano', hintHard: 'pula' },
      { w: 'Galinha', hint: 'ave doméstica', hintHard: 'ovo' },
      { w: 'Hipopótamo', hint: 'mamífero africano', hintHard: 'enorme' },
      { w: 'Rinoceronte', hint: 'mamífero com chifre', hintHard: 'chifre' },
      { w: 'Crocodilo', hint: 'réptil predador', hintHard: 'dentes' },
      { w: 'Caranguejo', hint: 'crustáceo', hintHard: 'pinças' },
      { w: 'Foca', hint: 'mamífero aquático', hintHard: 'ártico' },
    ],
  },
  {
    id: 'sports',
    emoji: '⚽',
    name: 'Esportes',
    words: [
      { w: 'Futebol', hint: 'esporte mais popular', hintHard: 'bola' },
      { w: 'Vôlei', hint: 'esporte de quadra', hintHard: 'rede alta' },
      { w: 'Basquete', hint: 'cesta', hintHard: 'quica' },
      { w: 'Tênis', hint: 'raquete', hintHard: 'amarela' },
      { w: 'Natação', hint: 'aquático', hintHard: 'molhado' },
      { w: 'Boxe', hint: 'luta', hintHard: 'luvas' },
      { w: 'Surfe', hint: 'esporte de praia', hintHard: 'onda' },
      { w: 'Skate', hint: 'esporte urbano', hintHard: 'rodinhas' },
      { w: 'Ciclismo', hint: 'sobre duas rodas', hintHard: 'pedal' },
      { w: 'Corrida', hint: 'atletismo', hintHard: 'rápido' },
      { w: 'Golfe', hint: 'esporte de elite', hintHard: 'taco' },
      { w: 'Beisebol', hint: 'esporte americano', hintHard: 'rebatedor' },
      { w: 'Handebol', hint: 'esporte com as mãos', hintHard: 'gol' },
      { w: 'Judô', hint: 'arte marcial japonesa', hintHard: 'kimono' },
      { w: 'Karatê', hint: 'arte marcial', hintHard: 'faixa' },
      { w: 'Ginástica', hint: 'flexibilidade', hintHard: 'salto' },
      { w: 'Patinação', hint: 'no gelo ou rodas', hintHard: 'deslizar' },
      { w: 'Vela', hint: 'esporte náutico', hintHard: 'vento' },
      { w: 'Escalada', hint: 'esporte de altura', hintHard: 'pedra' },
      { w: 'Rugby', hint: 'esporte britânico', hintHard: 'oval' },
      { w: 'Esgrima', hint: 'duelo', hintHard: 'espada' },
      { w: 'Polo Aquático', hint: 'esporte em piscina', hintHard: 'time na água' },
      { w: 'Tiro com Arco', hint: 'esporte de precisão', hintHard: 'flecha' },
      { w: 'Hipismo', hint: 'esporte com cavalo', hintHard: 'salto' },
      { w: 'Bocha', hint: 'esporte de bolas', hintHard: 'pontaria' },
      { w: 'Sinuca', hint: 'esporte de mesa', hintHard: 'taco' },
      { w: 'Triatlo', hint: 'três esportes seguidos', hintHard: 'resistência' },
      { w: 'Parkour', hint: 'esporte urbano', hintHard: 'salto' },
      { w: 'MMA', hint: 'luta livre', hintHard: 'octógono' },
      { w: 'Futsal', hint: 'futebol de quadra', hintHard: 'cinco jogadores' },
      { w: 'Snowboard', hint: 'esporte de inverno', hintHard: 'neve' },
    ],
  },
  {
    id: 'jobs',
    emoji: '👔',
    name: 'Profissões',
    words: [
      { w: 'Médico', hint: 'área da saúde', hintHard: 'jaleco' },
      { w: 'Professor', hint: 'educação', hintHard: 'quadro' },
      { w: 'Engenheiro', hint: 'constrói', hintHard: 'cálculos' },
      { w: 'Advogado', hint: 'tribunal', hintHard: 'beca' },
      { w: 'Bombeiro', hint: 'salva vidas', hintHard: 'fogo' },
      { w: 'Policial', hint: 'segurança', hintHard: 'farda' },
      { w: 'Cozinheiro', hint: 'cozinha', hintHard: 'chapéu' },
      { w: 'Cantor', hint: 'artista', hintHard: 'voz' },
      { w: 'Ator', hint: 'cinema', hintHard: 'palco' },
      { w: 'Dentista', hint: 'cuida dos dentes', hintHard: 'broca' },
      { w: 'Piloto', hint: 'aviação', hintHard: 'avião' },
      { w: 'Programador', hint: 'tecnologia', hintHard: 'código' },
      { w: 'Jornalista', hint: 'imprensa', hintHard: 'notícia' },
      { w: 'Arquiteto', hint: 'projetos', hintHard: 'planta' },
      { w: 'Veterinário', hint: 'cuida de animais', hintHard: 'clínica' },
      { w: 'Pintor', hint: 'artes', hintHard: 'tinta' },
      { w: 'Escritor', hint: 'livros', hintHard: 'palavras' },
      { w: 'Fotógrafo', hint: 'imagens', hintHard: 'clique' },
      { w: 'Mecânico', hint: 'oficina', hintHard: 'graxa' },
      { w: 'Padeiro', hint: 'padaria', hintHard: 'forno' },
      { w: 'Astronauta', hint: 'espaço', hintHard: 'capacete' },
      { w: 'Marceneiro', hint: 'trabalha com madeira', hintHard: 'móveis' },
      { w: 'Eletricista', hint: 'fios e energia', hintHard: 'circuito' },
      { w: 'Encanador', hint: 'consertos hidráulicos', hintHard: 'tubos' },
      { w: 'Garçom', hint: 'atende em restaurante', hintHard: 'bandeja' },
      { w: 'Motorista', hint: 'dirige', hintHard: 'volante' },
      { w: 'Entregador', hint: 'leva pedidos', hintHard: 'mochila' },
      { w: 'Barbeiro', hint: 'cuida do cabelo', hintHard: 'tesoura' },
      { w: 'Personal Trainer', hint: 'instrutor físico', hintHard: 'academia' },
      { w: 'Designer', hint: 'criação visual', hintHard: 'arte digital' },
      { w: 'YouTuber', hint: 'criador de vídeo', hintHard: 'câmera' },
    ],
  },
  {
    id: 'places',
    emoji: '🌍',
    name: 'Países & Lugares',
    words: [
      { w: 'Brasil', hint: 'país sul-americano', hintHard: 'verde e amarelo' },
      { w: 'Japão', hint: 'país asiático', hintHard: 'sol nascente' },
      { w: 'França', hint: 'país europeu', hintHard: 'torre' },
      { w: 'Itália', hint: 'país europeu', hintHard: 'bota' },
      { w: 'Egito', hint: 'norte da África', hintHard: 'pirâmide' },
      { w: 'Argentina', hint: 'vizinho do sul', hintHard: 'tango' },
      { w: 'Estados Unidos', hint: 'país americano', hintHard: 'estrelas' },
      { w: 'China', hint: 'país asiático', hintHard: 'muralha' },
      { w: 'México', hint: 'país americano', hintHard: 'sombrero' },
      { w: 'Austrália', hint: 'continente isolado', hintHard: 'canguru' },
      { w: 'Canadá', hint: 'norte do continente', hintHard: 'folha' },
      { w: 'Espanha', hint: 'europa ibérica', hintHard: 'flamenco' },
      { w: 'Portugal', hint: 'país europeu', hintHard: 'fado' },
      { w: 'Alemanha', hint: 'europa central', hintHard: 'cerveja' },
      { w: 'Rio de Janeiro', hint: 'cidade brasileira', hintHard: 'cristo' },
      { w: 'Paris', hint: 'capital europeia', hintHard: 'romance' },
      { w: 'Nova York', hint: 'cidade americana', hintHard: 'arranha-céu' },
      { w: 'Amazônia', hint: 'floresta', hintHard: 'verde' },
      { w: 'Saara', hint: 'deserto', hintHard: 'areia' },
      { w: 'Himalaia', hint: 'cordilheira', hintHard: 'altíssimo' },
      { w: 'Veneza', hint: 'cidade italiana', hintHard: 'canais' },
      { w: 'Londres', hint: 'capital inglesa', hintHard: 'big ben' },
      { w: 'Tóquio', hint: 'capital japonesa', hintHard: 'mega cidade' },
      { w: 'São Paulo', hint: 'maior cidade do Brasil', hintHard: 'metrópole' },
      { w: 'Salvador', hint: 'cidade baiana', hintHard: 'pelourinho' },
      { w: 'Suíça', hint: 'país europeu', hintHard: 'chocolate' },
      { w: 'Coreia do Sul', hint: 'país asiático', hintHard: 'kpop' },
      { w: 'Índia', hint: 'país asiático populoso', hintHard: 'taj mahal' },
      { w: 'Rússia', hint: 'maior país do mundo', hintHard: 'gélido' },
      { w: 'Disney', hint: 'parque temático', hintHard: 'mickey' },
      { w: 'Machu Picchu', hint: 'ruína inca', hintHard: 'altitude' },
    ],
  },
  {
    id: 'tech',
    emoji: '💻',
    name: 'Tecnologia',
    words: [
      { w: 'Internet', hint: 'rede mundial', hintHard: 'conexão' },
      { w: 'Smartphone', hint: 'celular moderno', hintHard: 'touch' },
      { w: 'Computador', hint: 'máquina de escritório', hintHard: 'teclado' },
      { w: 'Google', hint: 'gigante de busca', hintHard: 'pesquisa' },
      { w: 'YouTube', hint: 'plataforma de vídeo', hintHard: 'vermelho' },
      { w: 'Instagram', hint: 'rede social', hintHard: 'foto' },
      { w: 'WhatsApp', hint: 'mensagens', hintHard: 'verde' },
      { w: 'TikTok', hint: 'vídeos curtos', hintHard: 'viral' },
      { w: 'Netflix', hint: 'streaming', hintHard: 'séries' },
      { w: 'Inteligência Artificial', hint: 'tendência', hintHard: 'aprende' },
      { w: 'Robô', hint: 'máquina autônoma', hintHard: 'metal' },
      { w: 'Bluetooth', hint: 'conexão sem fio', hintHard: 'curto alcance' },
      { w: 'Wi-Fi', hint: 'rede sem fio', hintHard: 'invisível' },
      { w: 'Bateria', hint: 'energia portátil', hintHard: 'acaba' },
      { w: 'Headphone', hint: 'áudio pessoal', hintHard: 'orelha' },
      { w: 'Mouse', hint: 'periférico', hintHard: 'clica' },
      { w: 'Teclado', hint: 'periférico', hintHard: 'teclas' },
      { w: 'Tablet', hint: 'dispositivo móvel', hintHard: 'tela grande' },
      { w: 'Drone', hint: 'voador', hintHard: 'remoto' },
      { w: 'Realidade Virtual', hint: 'imersão', hintHard: 'óculos' },
      { w: 'Carregador', hint: 'energia', hintHard: 'fio' },
      { w: 'Pix', hint: 'pagamento brasileiro', hintHard: 'instantâneo' },
      { w: 'ChatGPT', hint: 'assistente IA', hintHard: 'conversa' },
      { w: 'Spotify', hint: 'streaming de música', hintHard: 'verde' },
      { w: 'Twitch', hint: 'plataforma de lives', hintHard: 'roxo' },
      { w: 'Discord', hint: 'chat por voz', hintHard: 'gamers' },
      { w: 'GPS', hint: 'localização', hintHard: 'mapa' },
      { w: 'Webcam', hint: 'câmera de PC', hintHard: 'reunião' },
      { w: 'Mouse Gamer', hint: 'periférico RGB', hintHard: 'colorido' },
      { w: 'Pen Drive', hint: 'armazenamento portátil', hintHard: 'USB' },
      { w: 'Roteador', hint: 'distribui internet', hintHard: 'antenas' },
    ],
  },
  {
    id: 'movies',
    emoji: '🎬',
    name: 'Filmes & Séries',
    words: [
      { w: 'Vingadores', hint: 'super-heróis', hintHard: 'equipe' },
      { w: 'Harry Potter', hint: 'bruxos', hintHard: 'óculos' },
      { w: 'Senhor dos Anéis', hint: 'fantasia épica', hintHard: 'jornada' },
      { w: 'Star Wars', hint: 'ficção espacial', hintHard: 'sabres' },
      { w: 'Matrix', hint: 'sci-fi', hintHard: 'pílula' },
      { w: 'Titanic', hint: 'romance trágico', hintHard: 'navio' },
      { w: 'Frozen', hint: 'animação', hintHard: 'gelo' },
      { w: 'Toy Story', hint: 'animação Pixar', hintHard: 'brinquedos' },
      { w: 'Stranger Things', hint: 'série Netflix', hintHard: 'anos 80' },
      { w: 'Breaking Bad', hint: 'série dramática', hintHard: 'químico' },
      { w: 'Game of Thrones', hint: 'série épica', hintHard: 'tronos' },
      { w: 'Round 6', hint: 'série coreana', hintHard: 'jogos' },
      { w: 'The Office', hint: 'série de comédia', hintHard: 'escritório' },
      { w: 'Friends', hint: 'sitcom', hintHard: 'sofá' },
      { w: 'La Casa de Papel', hint: 'série espanhola', hintHard: 'máscara' },
      { w: 'Avatar', hint: 'épico azul', hintHard: 'pandora' },
      { w: 'Coringa', hint: 'vilão DC', hintHard: 'risada' },
      { w: 'Batman', hint: 'morcego', hintHard: 'noite' },
      { w: 'Homem-Aranha', hint: 'super-herói', hintHard: 'teia' },
      { w: 'Pantera Negra', hint: 'super-herói', hintHard: 'wakanda' },
      { w: 'Wandinha', hint: 'série gótica', hintHard: 'tranças' },
      { w: 'Shrek', hint: 'animação verde', hintHard: 'ogro' },
      { w: 'Madagascar', hint: 'animação de zoo', hintHard: 'leão' },
      { w: 'Os Simpsons', hint: 'animação amarela', hintHard: 'família' },
      { w: 'Bob Esponja', hint: 'desenho aquático', hintHard: 'amarelo' },
      { w: 'Dragon Ball', hint: 'anime de lutas', hintHard: 'cabelo amarelo' },
      { w: 'Naruto', hint: 'anime ninja', hintHard: 'faixa na testa' },
      { w: 'Pokémon', hint: 'franquia japonesa', hintHard: 'pegar todos' },
      { w: 'Senhor Anéis', hint: 'épico fantasia', hintHard: 'anel' },
      { w: 'Tropa de Elite', hint: 'filme brasileiro', hintHard: 'caveirão' },
      { w: 'Cidade de Deus', hint: 'filme brasileiro', hintHard: 'favela' },
      { w: 'Velozes e Furiosos', hint: 'franquia de ação', hintHard: 'carros' },
    ],
  },
  {
    id: 'music',
    emoji: '🎵',
    name: 'Música & Estilos',
    words: [
      { w: 'Samba', hint: 'estilo brasileiro', hintHard: 'carnaval' },
      { w: 'Funk', hint: 'estilo brasileiro', hintHard: 'batida' },
      { w: 'Sertanejo', hint: 'estilo brasileiro', hintHard: 'campo' },
      { w: 'Pagode', hint: 'estilo brasileiro', hintHard: 'roda' },
      { w: 'Rock', hint: 'estilo internacional', hintHard: 'guitarra' },
      { w: 'Pop', hint: 'estilo popular', hintHard: 'top' },
      { w: 'Hip Hop', hint: 'cultura urbana', hintHard: 'rima' },
      { w: 'Reggae', hint: 'estilo jamaicano', hintHard: 'relax' },
      { w: 'Jazz', hint: 'estilo americano', hintHard: 'improvisa' },
      { w: 'Bossa Nova', hint: 'estilo brasileiro', hintHard: 'suave' },
      { w: 'Forró', hint: 'estilo nordestino', hintHard: 'sanfona' },
      { w: 'Eletrônica', hint: 'estilo digital', hintHard: 'beat' },
      { w: 'Metal', hint: 'estilo pesado', hintHard: 'pesado' },
      { w: 'Country', hint: 'estilo americano', hintHard: 'cowboy' },
      { w: 'Reggaeton', hint: 'estilo latino', hintHard: 'dembow' },
      { w: 'Blues', hint: 'estilo americano', hintHard: 'melancolia' },
      { w: 'Clássica', hint: 'estilo erudito', hintHard: 'orquestra' },
      { w: 'Trap', hint: 'subgênero hip hop', hintHard: '808' },
      { w: 'Indie', hint: 'estilo alternativo', hintHard: 'independente' },
      { w: 'Gospel', hint: 'estilo religioso', hintHard: 'fé' },
      { w: 'K-Pop', hint: 'estilo coreano', hintHard: 'idol' },
      { w: 'Punk', hint: 'estilo rebelde', hintHard: 'moicano' },
      { w: 'Disco', hint: 'estilo dos anos 70', hintHard: 'bola espelhada' },
      { w: 'Tecno', hint: 'estilo eletrônico', hintHard: 'rave' },
      { w: 'House', hint: 'estilo eletrônico', hintHard: 'four-on-floor' },
      { w: 'Soul', hint: 'estilo americano', hintHard: 'alma' },
      { w: 'R&B', hint: 'estilo americano', hintHard: 'romântico' },
      { w: 'Sertanejo Universitário', hint: 'subgênero brasileiro', hintHard: 'duplas' },
      { w: 'Brega', hint: 'estilo nordestino', hintHard: 'romântico' },
      { w: 'Lo-fi', hint: 'estilo relaxante', hintHard: 'estudo' },
      { w: 'Bolero', hint: 'estilo latino', hintHard: 'lento' },
    ],
  },
  {
    id: 'internet',
    emoji: '😂',
    name: 'Cultura da Internet',
    words: [
      { w: 'Meme', hint: 'piada da internet', hintHard: 'viral' },
      { w: 'Influencer', hint: 'criador de conteúdo', hintHard: 'seguidores' },
      { w: 'Live', hint: 'transmissão ao vivo', hintHard: 'agora' },
      { w: 'Hashtag', hint: 'marcação', hintHard: 'jogo da velha' },
      { w: 'Stories', hint: '24 horas', hintHard: 'some' },
      { w: 'Reels', hint: 'vídeo curto', hintHard: 'rolar' },
      { w: 'Cancelamento', hint: 'fenômeno social', hintHard: 'turba' },
      { w: 'Cringe', hint: 'sensação ruim', hintHard: 'vergonha' },
      { w: 'Shippar', hint: 'torcer por casal', hintHard: 'amor' },
      { w: 'Trend', hint: 'tendência viral', hintHard: 'todo mundo' },
      { w: 'Spoiler', hint: 'estraga surpresa', hintHard: 'cuidado' },
      { w: 'Stalker', hint: 'observador', hintHard: 'olha tudo' },
      { w: 'Crush', hint: 'paquera', hintHard: 'coração' },
      { w: 'Mood', hint: 'estado de espírito', hintHard: 'humor' },
      { w: 'Hater', hint: 'crítico', hintHard: 'detesta' },
      { w: 'Fake News', hint: 'desinformação', hintHard: 'mentira' },
      { w: 'Emoji', hint: 'caractere expressivo', hintHard: 'rosto' },
      { w: 'GIF', hint: 'imagem animada', hintHard: 'loop' },
      { w: 'Streamer', hint: 'cria conteúdo ao vivo', hintHard: 'twitch' },
      { w: 'Vlog', hint: 'diário em vídeo', hintHard: 'rotina' },
      { w: 'Podcast', hint: 'áudio sob demanda', hintHard: 'conversa' },
      { w: 'Print', hint: 'captura de tela', hintHard: 'evidência' },
      { w: 'NFT', hint: 'arte digital', hintHard: 'blockchain' },
      { w: 'Cancelado', hint: 'fenômeno social', hintHard: 'exposto' },
      { w: 'Engajamento', hint: 'métrica social', hintHard: 'likes' },
      { w: 'Bot', hint: 'conta automática', hintHard: 'robô' },
      { w: 'Tag', hint: 'marcar alguém', hintHard: 'arroba' },
      { w: 'Filtro', hint: 'efeito visual', hintHard: 'rosto' },
      { w: 'Throwback', hint: 'lembrança antiga', hintHard: 'foto velha' },
      { w: 'OOTD', hint: 'sigla de moda', hintHard: 'look do dia' },
      { w: 'Unboxing', hint: 'tipo de vídeo', hintHard: 'caixa' },
    ],
  },
  {
    id: 'hobbies',
    emoji: '🎯',
    name: 'Hobbies & Atividades',
    words: [
      { w: 'Leitura', hint: 'passatempo solitário', hintHard: 'silêncio' },
      { w: 'Pescaria', hint: 'paciência', hintHard: 'água' },
      { w: 'Jardinagem', hint: 'cuidar de plantas', hintHard: 'terra' },
      { w: 'Fotografia', hint: 'arte visual', hintHard: 'instante' },
      { w: 'Pintura', hint: 'arte visual', hintHard: 'pincel' },
      { w: 'Tricô', hint: 'artesanato', hintHard: 'agulhas' },
      { w: 'Caminhada', hint: 'exercício leve', hintHard: 'passos' },
      { w: 'Yoga', hint: 'prática corporal', hintHard: 'tapete' },
      { w: 'Cozinhar', hint: 'preparar comida', hintHard: 'fogão' },
      { w: 'Videogame', hint: 'entretenimento digital', hintHard: 'controle' },
      { w: 'Xadrez', hint: 'jogo de tabuleiro', hintHard: 'rei' },
      { w: 'Cinema', hint: 'sair com amigos', hintHard: 'pipoca' },
      { w: 'Dançar', hint: 'movimento ritmado', hintHard: 'pista' },
      { w: 'Cantar', hint: 'expressão vocal', hintHard: 'voz' },
      { w: 'Camping', hint: 'natureza', hintHard: 'barraca' },
      { w: 'Origami', hint: 'arte de dobrar', hintHard: 'papel' },
      { w: 'Crossfit', hint: 'treino intenso', hintHard: 'peso' },
      { w: 'Karaokê', hint: 'cantar sem profissão', hintHard: 'microfone' },
      { w: 'Trilha', hint: 'caminhada na mata', hintHard: 'pé na estrada' },
      { w: 'Crochê', hint: 'artesanato', hintHard: 'fio' },
      { w: 'Maratona de séries', hint: 'lazer', hintHard: 'sofá' },
      { w: 'Bordado', hint: 'artesanato', hintHard: 'agulha' },
      { w: 'Cerâmica', hint: 'arte com barro', hintHard: 'roda' },
      { w: 'Astronomia', hint: 'observar o céu', hintHard: 'telescópio' },
      { w: 'Geocaching', hint: 'caça ao tesouro', hintHard: 'GPS' },
      { w: 'Mergulho', hint: 'esporte aquático', hintHard: 'cilindro' },
      { w: 'Escalada Indoor', hint: 'esporte vertical', hintHard: 'paredão' },
      { w: 'Modelismo', hint: 'montar miniaturas', hintHard: 'colar' },
      { w: 'Boardgames', hint: 'jogos de tabuleiro', hintHard: 'peças' },
      { w: 'Mecânica de Bike', hint: 'manutenção', hintHard: 'óleo' },
      { w: 'Caligrafia', hint: 'escrita artística', hintHard: 'pena' },
    ],
  },
  {
    id: 'emotions',
    emoji: '😊',
    name: 'Emoções & Sentimentos',
    words: [
      { w: 'Alegria', hint: 'sentimento positivo', hintHard: 'sorriso' },
      { w: 'Tristeza', hint: 'sentimento negativo', hintHard: 'lágrimas' },
      { w: 'Raiva', hint: 'sentimento forte', hintHard: 'rosto vermelho' },
      { w: 'Medo', hint: 'sentimento de perigo', hintHard: 'tremer' },
      { w: 'Amor', hint: 'sentimento universal', hintHard: 'coração' },
      { w: 'Ódio', hint: 'sentimento oposto', hintHard: 'rejeição' },
      { w: 'Saudade', hint: 'sentimento brasileiro', hintHard: 'distância' },
      { w: 'Inveja', hint: 'sentimento incômodo', hintHard: 'olhar' },
      { w: 'Vergonha', hint: 'sentimento social', hintHard: 'corar' },
      { w: 'Orgulho', hint: 'sentimento próprio', hintHard: 'peito estufado' },
      { w: 'Ansiedade', hint: 'sentimento atual', hintHard: 'preocupação' },
      { w: 'Calma', hint: 'estado tranquilo', hintHard: 'respirar' },
      { w: 'Surpresa', hint: 'reação inesperada', hintHard: 'olhos arregalados' },
      { w: 'Confiança', hint: 'segurança', hintHard: 'certeza' },
      { w: 'Esperança', hint: 'expectativa positiva', hintHard: 'futuro' },
      { w: 'Curiosidade', hint: 'vontade de saber', hintHard: 'perguntas' },
      { w: 'Gratidão', hint: 'agradecimento', hintHard: 'obrigado' },
      { w: 'Solidão', hint: 'sentir-se só', hintHard: 'sozinho' },
      { w: 'Coragem', hint: 'enfrentar', hintHard: 'sem medo' },
      { w: 'Euforia', hint: 'alegria intensa', hintHard: 'pular' },
      { w: 'Decepção', hint: 'expectativa quebrada', hintHard: 'frustração' },
      { w: 'Empolgação', hint: 'sentimento intenso', hintHard: 'animação' },
      { w: 'Frustração', hint: 'sentimento negativo', hintHard: 'travado' },
      { w: 'Compaixão', hint: 'sentimento empático', hintHard: 'doer pelo outro' },
      { w: 'Inspiração', hint: 'momento criativo', hintHard: 'ideia' },
      { w: 'Saudosismo', hint: 'lembrança passada', hintHard: 'antigamente' },
      { w: 'Estresse', hint: 'tensão emocional', hintHard: 'sobrecarga' },
      { w: 'Tédio', hint: 'falta de interesse', hintHard: 'sem graça' },
      { w: 'Vingança', hint: 'devolver mal', hintHard: 'olho por olho' },
      { w: 'Adoração', hint: 'amor profundo', hintHard: 'idolatrar' },
      { w: 'Despeito', hint: 'mágoa de não ter', hintHard: 'rancor' },
    ],
  },
  {
    id: 'colors',
    emoji: '🎨',
    name: 'Cores & Formas',
    words: [
      { w: 'Vermelho', hint: 'cor primária', hintHard: 'fogo' },
      { w: 'Azul', hint: 'cor primária', hintHard: 'céu' },
      { w: 'Amarelo', hint: 'cor primária', hintHard: 'sol' },
      { w: 'Verde', hint: 'cor secundária', hintHard: 'mato' },
      { w: 'Laranja', hint: 'cor secundária', hintHard: 'fruta' },
      { w: 'Roxo', hint: 'cor secundária', hintHard: 'uva' },
      { w: 'Rosa', hint: 'cor terciária', hintHard: 'flor' },
      { w: 'Preto', hint: 'tom escuro', hintHard: 'sombra' },
      { w: 'Branco', hint: 'tom claro', hintHard: 'neve' },
      { w: 'Marrom', hint: 'tom terroso', hintHard: 'chocolate' },
      { w: 'Cinza', hint: 'tom neutro', hintHard: 'pedra' },
      { w: 'Círculo', hint: 'forma redonda', hintHard: 'sem cantos' },
      { w: 'Quadrado', hint: 'forma simétrica', hintHard: 'lados iguais' },
      { w: 'Triângulo', hint: 'três lados', hintHard: 'pico' },
      { w: 'Retângulo', hint: 'duas medidas', hintHard: 'porta' },
      { w: 'Estrela', hint: 'forma celestial', hintHard: 'pontas' },
      { w: 'Coração', hint: 'forma amorosa', hintHard: 'amor' },
      { w: 'Losango', hint: 'quadrado torto', hintHard: 'pipa' },
      { w: 'Cubo', hint: 'forma 3D', hintHard: 'dado' },
      { w: 'Esfera', hint: 'forma 3D', hintHard: 'bola' },
      { w: 'Pirâmide', hint: 'forma 3D', hintHard: 'egito' },
      { w: 'Turquesa', hint: 'tom azul-verde', hintHard: 'pedra' },
      { w: 'Bege', hint: 'tom claro neutro', hintHard: 'café com leite' },
      { w: 'Dourado', hint: 'tom metálico', hintHard: 'ouro' },
      { w: 'Prateado', hint: 'tom metálico', hintHard: 'prata' },
      { w: 'Vinho', hint: 'tom de vermelho', hintHard: 'bordô' },
      { w: 'Pistache', hint: 'tom verde claro', hintHard: 'sorvete' },
      { w: 'Cilindro', hint: 'forma 3D', hintHard: 'rolinho' },
      { w: 'Cone', hint: 'forma 3D', hintHard: 'sorvete' },
      { w: 'Oval', hint: 'forma alongada', hintHard: 'esticada' },
      { w: 'Trapézio', hint: 'forma geométrica', hintHard: 'lados paralelos' },
    ],
  },
  {
    id: 'objects',
    emoji: '🏠',
    name: 'Objetos do Cotidiano',
    words: [
      { w: 'Chave', hint: 'abre portas', hintHard: 'metal' },
      { w: 'Carteira', hint: 'guarda dinheiro', hintHard: 'bolso' },
      { w: 'Escova de Dentes', hint: 'higiene', hintHard: 'cerdas' },
      { w: 'Travesseiro', hint: 'dormir', hintHard: 'cabeça' },
      { w: 'Espelho', hint: 'reflete', hintHard: 'imagem' },
      { w: 'Tesoura', hint: 'corta', hintHard: 'duas lâminas' },
      { w: 'Garfo', hint: 'utensílio', hintHard: 'dentes' },
      { w: 'Faca', hint: 'utensílio', hintHard: 'corta' },
      { w: 'Colher', hint: 'utensílio', hintHard: 'sopa' },
      { w: 'Guarda-Chuva', hint: 'chuva', hintHard: 'abre' },
      { w: 'Óculos', hint: 'enxergar', hintHard: 'lentes' },
      { w: 'Relógio', hint: 'tempo', hintHard: 'horas' },
      { w: 'Mochila', hint: 'leva coisas', hintHard: 'costas' },
      { w: 'Caderno', hint: 'escola', hintHard: 'folhas' },
      { w: 'Caneta', hint: 'escrita', hintHard: 'tinta' },
      { w: 'Sofá', hint: 'sala', hintHard: 'sentar' },
      { w: 'Geladeira', hint: 'cozinha', hintHard: 'gelada' },
      { w: 'Televisão', hint: 'eletrônico', hintHard: 'tela' },
      { w: 'Cama', hint: 'quarto', hintHard: 'dormir' },
      { w: 'Vassoura', hint: 'limpeza', hintHard: 'cabo longo' },
      { w: 'Ventilador', hint: 'verão', hintHard: 'pás' },
      { w: 'Micro-ondas', hint: 'eletrodoméstico', hintHard: 'esquenta' },
      { w: 'Liquidificador', hint: 'cozinha', hintHard: 'lâminas' },
      { w: 'Máquina de Lavar', hint: 'área de serviço', hintHard: 'roupas' },
      { w: 'Aspirador', hint: 'limpeza', hintHard: 'suga' },
      { w: 'Pente', hint: 'cabelo', hintHard: 'dentes' },
      { w: 'Carteira de Identidade', hint: 'documento', hintHard: 'foto' },
      { w: 'Celular', hint: 'comunicação', hintHard: 'na mão' },
      { w: 'Carregador de Celular', hint: 'cabo', hintHard: 'energia' },
      { w: 'Capacete', hint: 'proteção', hintHard: 'cabeça' },
      { w: 'Almofada', hint: 'decoração', hintHard: 'macio' },
    ],
  },
  {
    id: 'nature',
    emoji: '🌿',
    name: 'Natureza & Clima',
    words: [
      { w: 'Chuva', hint: 'clima', hintHard: 'molha' },
      { w: 'Sol', hint: 'clima', hintHard: 'amarelo' },
      { w: 'Neve', hint: 'clima', hintHard: 'branca' },
      { w: 'Vento', hint: 'clima', hintHard: 'invisível' },
      { w: 'Trovão', hint: 'clima', hintHard: 'barulho' },
      { w: 'Relâmpago', hint: 'clima', hintHard: 'luz' },
      { w: 'Arco-Íris', hint: 'depois da chuva', hintHard: 'cores' },
      { w: 'Nuvem', hint: 'céu', hintHard: 'branca' },
      { w: 'Praia', hint: 'lugar', hintHard: 'areia' },
      { w: 'Montanha', hint: 'lugar', hintHard: 'alto' },
      { w: 'Rio', hint: 'água doce', hintHard: 'corre' },
      { w: 'Oceano', hint: 'água salgada', hintHard: 'enorme' },
      { w: 'Floresta', hint: 'verde', hintHard: 'árvores' },
      { w: 'Deserto', hint: 'seco', hintHard: 'areia' },
      { w: 'Vulcão', hint: 'natureza ardente', hintHard: 'lava' },
      { w: 'Terremoto', hint: 'desastre', hintHard: 'tremor' },
      { w: 'Furacão', hint: 'desastre', hintHard: 'roda' },
      { w: 'Estrela', hint: 'no céu', hintHard: 'brilha' },
      { w: 'Lua', hint: 'astro', hintHard: 'noite' },
      { w: 'Cachoeira', hint: 'água que cai', hintHard: 'altura' },
      { w: 'Pôr do Sol', hint: 'fim do dia', hintHard: 'laranja' },
      { w: 'Geada', hint: 'clima frio', hintHard: 'cristais' },
      { w: 'Tornado', hint: 'fenômeno climático', hintHard: 'funil' },
      { w: 'Tsunami', hint: 'desastre natural', hintHard: 'onda gigante' },
      { w: 'Aurora Boreal', hint: 'fenômeno luminoso', hintHard: 'norte gelado' },
      { w: 'Lago', hint: 'corpo d\'água', hintHard: 'parado' },
      { w: 'Caverna', hint: 'formação rochosa', hintHard: 'escura' },
      { w: 'Bosque', hint: 'pequena floresta', hintHard: 'árvores' },
      { w: 'Pântano', hint: 'área alagada', hintHard: 'lama' },
      { w: 'Iceberg', hint: 'gelo enorme', hintHard: 'oceano' },
      { w: 'Eclipse', hint: 'fenômeno celeste', hintHard: 'sol some' },
    ],
  },
  {
    id: 'celebs',
    emoji: '⭐',
    name: 'Celebridades & Famosos',
    words: [
      { w: 'Pelé', hint: 'lenda do futebol', hintHard: 'rei' },
      { w: 'Neymar', hint: 'jogador brasileiro', hintHard: 'craque' },
      { w: 'Messi', hint: 'jogador argentino', hintHard: 'baixinho' },
      { w: 'Cristiano Ronaldo', hint: 'jogador português', hintHard: 'siuuu' },
      { w: 'Anitta', hint: 'cantora brasileira', hintHard: 'envolvente' },
      { w: 'Ivete Sangalo', hint: 'cantora baiana', hintHard: 'axé' },
      { w: 'Xuxa', hint: 'rainha dos baixinhos', hintHard: 'loira' },
      { w: 'Silvio Santos', hint: 'apresentador', hintHard: 'auditório' },
      { w: 'Faustão', hint: 'apresentador', hintHard: 'olha ele aí' },
      { w: 'Beyoncé', hint: 'cantora americana', hintHard: 'diva' },
      { w: 'Taylor Swift', hint: 'cantora americana', hintHard: 'eras' },
      { w: 'Elon Musk', hint: 'empresário', hintHard: 'foguete' },
      { w: 'Bill Gates', hint: 'empresário', hintHard: 'windows' },
      { w: 'Steve Jobs', hint: 'empresário', hintHard: 'maçã' },
      { w: 'Einstein', hint: 'cientista', hintHard: 'cabelo branco' },
      { w: 'Michael Jackson', hint: 'rei do pop', hintHard: 'moonwalk' },
      { w: 'Madonna', hint: 'rainha do pop', hintHard: 'reinvenção' },
      { w: 'Senna', hint: 'piloto brasileiro', hintHard: 'capacete' },
      { w: 'Hebe Camargo', hint: 'apresentadora', hintHard: 'beijinho' },
      { w: 'Gugu Liberato', hint: 'apresentador', hintHard: 'domingo' },
      { w: 'Whindersson Nunes', hint: 'humorista', hintHard: 'piauí' },
      { w: 'Felipe Neto', hint: 'youtuber', hintHard: 'polêmico' },
      { w: 'Casimiro', hint: 'streamer brasileiro', hintHard: 'reage' },
      { w: 'Galvão Bueno', hint: 'narrador', hintHard: 'haja coração' },
      { w: 'Roberto Carlos', hint: 'rei brasileiro', hintHard: 'detalhes' },
      { w: 'Caetano Veloso', hint: 'mpb', hintHard: 'tropicália' },
      { w: 'Gisele Bündchen', hint: 'modelo brasileira', hintHard: 'passarela' },
      { w: 'Steven Spielberg', hint: 'diretor', hintHard: 'blockbusters' },
      { w: 'Cristina Kirchner', hint: 'política argentina', hintHard: 'ex-presidenta' },
      { w: 'Luva de Pedreiro', hint: 'influencer', hintHard: 'receba' },
      { w: 'MC Daniel', hint: 'funkeiro', hintHard: 'tabajara' },
    ],
  },

  // --- NEW CATEGORIES ---

  {
    id: 'videogames',
    emoji: '🎮',
    name: 'Videogames',
    words: [
      { w: 'Minecraft', hint: 'jogo de blocos', hintHard: 'criação' },
      { w: 'Fortnite', hint: 'battle royale', hintHard: 'dança' },
      { w: 'Roblox', hint: 'plataforma de jogos', hintHard: 'crianças' },
      { w: 'Free Fire', hint: 'battle royale mobile', hintHard: 'tiro' },
      { w: 'Counter-Strike', hint: 'fps clássico', hintHard: 'bomba' },
      { w: 'League of Legends', hint: 'moba', hintHard: 'cinco contra cinco' },
      { w: 'Valorant', hint: 'fps tático', hintHard: 'agentes' },
      { w: 'GTA', hint: 'mundo aberto', hintHard: 'crime' },
      { w: 'FIFA', hint: 'jogo de futebol', hintHard: 'simulação' },
      { w: 'Call of Duty', hint: 'fps militar', hintHard: 'tiro' },
      { w: 'The Sims', hint: 'simulação de vida', hintHard: 'plumbob' },
      { w: 'Super Mario', hint: 'plataforma', hintHard: 'encanador' },
      { w: 'Zelda', hint: 'aventura', hintHard: 'link' },
      { w: 'Tetris', hint: 'puzzle clássico', hintHard: 'blocos' },
      { w: 'Pac-Man', hint: 'fliperama', hintHard: 'come bolinhas' },
      { w: 'Sonic', hint: 'plataforma', hintHard: 'ouriço azul' },
      { w: 'Street Fighter', hint: 'luta clássica', hintHard: 'hadouken' },
      { w: 'Tekken', hint: 'luta 3D', hintHard: 'combos' },
      { w: 'God of War', hint: 'ação aventura', hintHard: 'kratos' },
      { w: 'The Witcher', hint: 'rpg', hintHard: 'caçador' },
      { w: 'Among Us', hint: 'social deduction', hintHard: 'também tem impostor' },
      { w: 'Stardew Valley', hint: 'fazendinha', hintHard: 'plantar' },
      { w: 'Resident Evil', hint: 'survival horror', hintHard: 'zumbis' },
      { w: 'Mortal Kombat', hint: 'luta sangrenta', hintHard: 'fatality' },
      { w: 'Genshin Impact', hint: 'rpg gacha', hintHard: 'anime' },
    ],
  },

  {
    id: 'brands',
    emoji: '🏷️',
    name: 'Marcas Famosas',
    words: [
      { w: 'Coca-Cola', hint: 'refrigerante', hintHard: 'vermelho' },
      { w: 'Pepsi', hint: 'refrigerante', hintHard: 'azul' },
      { w: 'McDonald\'s', hint: 'fast food', hintHard: 'M dourado' },
      { w: 'Burger King', hint: 'fast food', hintHard: 'rei' },
      { w: 'Subway', hint: 'sanduíches', hintHard: 'metrô' },
      { w: 'Nike', hint: 'esportivo', hintHard: 'swoosh' },
      { w: 'Adidas', hint: 'esportivo', hintHard: 'três listras' },
      { w: 'Apple', hint: 'eletrônicos', hintHard: 'maçã' },
      { w: 'Samsung', hint: 'eletrônicos', hintHard: 'coreana' },
      { w: 'Sony', hint: 'eletrônicos', hintHard: 'playstation' },
      { w: 'Microsoft', hint: 'tecnologia', hintHard: 'janelinhas' },
      { w: 'Amazon', hint: 'e-commerce', hintHard: 'sorriso' },
      { w: 'Mercado Livre', hint: 'e-commerce BR', hintHard: 'amarelo' },
      { w: 'iFood', hint: 'delivery brasileiro', hintHard: 'vermelho' },
      { w: 'Uber', hint: 'transporte', hintHard: 'app' },
      { w: '99', hint: 'transporte BR', hintHard: 'amarelo' },
      { w: 'Nubank', hint: 'banco digital', hintHard: 'roxo' },
      { w: 'Havaianas', hint: 'sandália brasileira', hintHard: 'praia' },
      { w: 'Bombril', hint: 'palha de aço', hintHard: 'utilidades' },
      { w: 'Brastemp', hint: 'eletrodoméstico', hintHard: 'tem que ser' },
      { w: 'Lego', hint: 'brinquedo', hintHard: 'encaixar' },
      { w: 'Nintendo', hint: 'videogame', hintHard: 'mario' },
      { w: 'Volkswagen', hint: 'carro alemão', hintHard: 'fusca' },
      { w: 'Toyota', hint: 'carro japonês', hintHard: 'corolla' },
      { w: 'Tesla', hint: 'carro elétrico', hintHard: 'musk' },
    ],
  },

  {
    id: 'cars',
    emoji: '🚗',
    name: 'Carros & Veículos',
    words: [
      { w: 'Fusca', hint: 'carro clássico', hintHard: 'redondinho' },
      { w: 'Gol', hint: 'carro popular brasileiro', hintHard: 'Volkswagen' },
      { w: 'Civic', hint: 'sedan japonês', hintHard: 'Honda' },
      { w: 'Corolla', hint: 'sedan japonês', hintHard: 'Toyota' },
      { w: 'Hilux', hint: 'caminhonete', hintHard: 'Toyota' },
      { w: 'Camaro', hint: 'esportivo americano', hintHard: 'amarelo do Bumblebee' },
      { w: 'Mustang', hint: 'esportivo americano', hintHard: 'cavalo' },
      { w: 'Ferrari', hint: 'esportivo italiano', hintHard: 'vermelho' },
      { w: 'Lamborghini', hint: 'super esportivo', hintHard: 'touro' },
      { w: 'Porsche', hint: 'esportivo alemão', hintHard: '911' },
      { w: 'BMW', hint: 'carro alemão', hintHard: 'azul e branco' },
      { w: 'Mercedes', hint: 'luxo alemão', hintHard: 'estrela de três pontas' },
      { w: 'Jeep', hint: 'off-road', hintHard: 'Renegade' },
      { w: 'Caminhão', hint: 'veículo grande', hintHard: 'carga' },
      { w: 'Moto', hint: 'duas rodas motorizadas', hintHard: 'capacete' },
      { w: 'Trator', hint: 'veículo agrícola', hintHard: 'fazenda' },
      { w: 'Ônibus', hint: 'transporte público', hintHard: 'parada' },
      { w: 'Trem', hint: 'sobre trilhos', hintHard: 'vagões' },
      { w: 'Metrô', hint: 'transporte urbano', hintHard: 'subterrâneo' },
      { w: 'Avião', hint: 'transporte aéreo', hintHard: 'asas' },
      { w: 'Helicóptero', hint: 'aéreo com hélice', hintHard: 'rotor' },
      { w: 'Barco', hint: 'aquático', hintHard: 'flutua' },
      { w: 'Lancha', hint: 'barco rápido', hintHard: 'motor' },
      { w: 'Bicicleta', hint: 'sem motor', hintHard: 'pedais' },
      { w: 'Patinete', hint: 'urbano elétrico', hintHard: 'duas rodas pequenas' },
    ],
  },

  {
    id: 'desserts',
    emoji: '🍰',
    name: 'Doces & Sobremesas',
    words: [
      { w: 'Bolo de Aniversário', hint: 'festa', hintHard: 'velinhas' },
      { w: 'Pudim', hint: 'sobremesa cremosa', hintHard: 'caramelo' },
      { w: 'Quindim', hint: 'sobremesa amarela', hintHard: 'coco' },
      { w: 'Beijinho', hint: 'doce de festa', hintHard: 'coco branco' },
      { w: 'Cocada', hint: 'doce de coco', hintHard: 'baiana' },
      { w: 'Cupcake', hint: 'bolinho individual', hintHard: 'cobertura' },
      { w: 'Donut', hint: 'rosquinha', hintHard: 'furo no meio' },
      { w: 'Macaron', hint: 'doce francês', hintHard: 'colorido' },
      { w: 'Cheesecake', hint: 'torta de queijo', hintHard: 'frutas vermelhas' },
      { w: 'Petit Gâteau', hint: 'bolinho quente', hintHard: 'recheio derretido' },
      { w: 'Tiramisu', hint: 'sobremesa italiana', hintHard: 'café' },
      { w: 'Banoffee', hint: 'torta inglesa', hintHard: 'banana e doce de leite' },
      { w: 'Sorvete de Casquinha', hint: 'verão', hintHard: 'cone' },
      { w: 'Açaí na Tigela', hint: 'comida saudável', hintHard: 'granola' },
      { w: 'Brownie', hint: 'massa de chocolate', hintHard: 'denso' },
      { w: 'Mousse de Maracujá', hint: 'sobremesa azedinha', hintHard: 'amarela' },
      { w: 'Romeu e Julieta', hint: 'queijo + goiabada', hintHard: 'mineiro' },
      { w: 'Paçoca', hint: 'doce de amendoim', hintHard: 'farelinho' },
      { w: 'Pé de Moleque', hint: 'doce de amendoim', hintHard: 'crocante' },
      { w: 'Bala', hint: 'guloseima pequena', hintHard: 'açucarada' },
      { w: 'Pirulito', hint: 'bala com palito', hintHard: 'redondo' },
      { w: 'Chiclete', hint: 'mastigar', hintHard: 'bola' },
      { w: 'Algodão Doce', hint: 'parque de diversões', hintHard: 'rosa fofo' },
      { w: 'Maçã do Amor', hint: 'doce de parque', hintHard: 'caramelo vermelho' },
      { w: 'Fondue', hint: 'experiência gourmet', hintHard: 'chocolate derretido' },
    ],
  },

  {
    id: 'br_culture',
    emoji: '🇧🇷',
    name: 'Cultura Pop BR',
    words: [
      { w: 'BBB', hint: 'reality show', hintHard: 'big brother' },
      { w: 'A Fazenda', hint: 'reality show', hintHard: 'roça' },
      { w: 'Casamento Blindado', hint: 'reality de casal', hintHard: 'desafios' },
      { w: 'Jornal Nacional', hint: 'tele jornal', hintHard: 'oito horas' },
      { w: 'Globo', hint: 'emissora de TV', hintHard: 'plim plim' },
      { w: 'Carnaval', hint: 'festa popular', hintHard: 'samba' },
      { w: 'Réveillon', hint: 'virada do ano', hintHard: 'branco' },
      { w: 'Festa Junina', hint: 'festa de junho', hintHard: 'quadrilha' },
      { w: 'Páscoa', hint: 'feriado', hintHard: 'chocolate' },
      { w: 'Dia das Mães', hint: 'feriado familiar', hintHard: 'maio' },
      { w: 'Black Friday', hint: 'data comercial', hintHard: 'metade do dobro' },
      { w: 'Olimpíadas', hint: 'evento esportivo', hintHard: 'tochas' },
      { w: 'Copa do Mundo', hint: 'evento esportivo', hintHard: 'futebol' },
      { w: 'Rock in Rio', hint: 'festival de música', hintHard: 'palco mundo' },
      { w: 'Lollapalooza', hint: 'festival', hintHard: 'interlagos' },
      { w: 'Marketplace', hint: 'tecnologia', hintHard: 'compras online' },
      { w: 'Pix', hint: 'pagamento', hintHard: 'instantâneo' },
      { w: 'WhatsApp', hint: 'mensagens', hintHard: 'verde' },
      { w: 'Lan House', hint: 'memória dos 2000', hintHard: 'jogar online' },
      { w: 'Mensageiro', hint: 'app antigo', hintHard: 'MSN' },
      { w: 'Orkut', hint: 'rede social antiga', hintHard: 'comunidades' },
      { w: 'Casinha de Boneca', hint: 'brinquedo de criança', hintHard: 'miniatura' },
      { w: 'Pipa', hint: 'brincadeira de rua', hintHard: 'no céu' },
      { w: 'Bafo', hint: 'brincadeira nostálgica', hintHard: 'figurinhas' },
      { w: 'Bets', hint: 'fenômeno recente', hintHard: 'apostar' },
    ],
  },
];
